import { describe, expect, it } from "vitest";
import { parseTasks, completeLine, redateLine, dueByToday } from "../src/engine/collectors/tasks";
import { parseAnnouncements } from "../src/engine/collectors/announcements";
import { parseRadar } from "../src/engine/collectors/radar";
import { daysBetween, addDays } from "../src/util/dates";
import { coerceState } from "../src/state/schema";

describe("parseTasks", () => {
  it("ignores checklists outside Tasks/Actions headings", () => {
    const md = "## Study\n- [ ] read ch1\n- [ ] read ch2\n## Tasks\n- [ ] submit A1 📅 2026-10-02\n";
    const t = parseTasks("a.md", md);
    expect(t).toHaveLength(1);
    expect(t[0].due).toBe("2026-10-02");
    expect(t[0].text).toBe("submit A1");
    expect(t[0].line).toBe(4);
  });
  it("counts #task anywhere and skips code fences and frontmatter", () => {
    const md = "---\ntags: x\n---\n## Notes\n- [ ] loose #task thing\n```\n## Tasks\n- [ ] fake\n```\n";
    expect(parseTasks("a.md", md).map((t) => t.text)).toEqual(["loose #task thing"]);
  });
  it("detects done, waiting and priority", () => {
    const [a, b] = parseTasks("a.md", "## Actions\n- [x] done ✅ 2026-09-28\n- [ ] ping Sam #waiting ⏫\n");
    expect(a.done).toBe(true);
    expect(a.doneDate).toBe("2026-09-28");
    expect(b.waiting).toBe(true);
    expect(b.priority).toBe(1);
  });
  it("selects overdue and due-today only", () => {
    const t = parseTasks("a.md", "## Tasks\n- [ ] a 📅 2026-09-30\n- [ ] b 📅 2026-10-02\n- [ ] c 📅 2026-10-05\n- [ ] d\n");
    expect(dueByToday(t, "2026-10-02").map((x) => x.text)).toEqual(["a", "b"]);
  });
});

describe("line edits", () => {
  it("completes with the real date", () => {
    expect(completeLine("- [ ] x 📅 2026-10-01", "2026-10-02")).toBe("- [x] x 📅 2026-10-01 ✅ 2026-10-02");
  });
  it("re-dates in place or appends", () => {
    expect(redateLine("- [ ] x 📅 2026-10-01", "2026-10-09")).toBe("- [ ] x 📅 2026-10-09");
    expect(redateLine("- [ ] x", "2026-10-09")).toBe("- [ ] x 📅 2026-10-09");
  });
});

describe("parseAnnouncements", () => {
  const md = `## 📣 Now\n\n<!-- pa:announcements:start -->\n*Updated Thu 1 Oct, 21:22*\n\n- 🔴 **DS346 A1 is due tomorrow.** Confirm.\n- 🗓 **Rituals due.**\n- ⚠️ **No journal since 30 Sep.**\n<!-- pa:announcements:end -->`;
  it("reads levels, text and updated stamp", () => {
    const r = parseAnnouncements(md);
    expect(r.updated).toBe("Thu 1 Oct, 21:22");
    expect(r.items.map((i) => i.level)).toEqual(["urgent", "info", "stale"]);
    expect(r.items[1].text).toBe("**Rituals due.**");
    expect(new Set(r.items.map((i) => i.id)).size).toBe(3);
  });
  it("returns nothing without markers", () => {
    expect(parseAnnouncements("# hi").items).toEqual([]);
  });
});

describe("parseRadar", () => {
  const md = `## 📊 Deadline radar\n\n*note*\n\n| Score | Assessment | Due | Weight | Days |\n|---|---|---|---|---|\n| **20.0** | DS346 A1 — NLP | Fri 2 Oct | 40 | 2 |\n| — | CS343 Project 2 | Tue 13 Oct, 17:00 | $F = RM$ | 13 |\n\n**Read:** x\n\n## Next`;
  it("parses scored and unscored rows", () => {
    const r = parseRadar(md);
    expect(r).toHaveLength(2);
    expect(r[0]).toMatchObject({ name: "DS346 A1 — NLP", score: 20, days: 2, weightText: "40" });
    expect(r[1].score).toBeUndefined();
  });
});

describe("dates and state", () => {
  it("does date maths", () => {
    expect(daysBetween("2026-09-28", "2026-10-02")).toBe(4);
    expect(addDays("2026-09-30", 1)).toBe("2026-10-01");
  });
  it("repairs bad state", () => {
    expect(coerceState(null).schemaVersion).toBe(1);
    expect(coerceState({ schemaVersion: 2 }).interactions.acks).toEqual({});
    expect(coerceState({ schemaVersion: 1, interactions: { acks: { a: "x", b: 3 } } }).interactions.acks).toEqual({ a: "x" });
  });
});

import { analyzeJournal, summarizeJournal } from "../src/engine/collectors/journal";
import { scoreRadar } from "../src/engine/collectors/radar";
import { engineAnnouncements } from "../src/engine/collectors/staleness";
import { findDuplicates } from "../src/engine/collectors/duplicates";
import { parseDueText, dailyNameToIso } from "../src/util/dates";

const TEMPLATE = `---\ndate: 2026-10-02\n---\n\n# Friday\n\n## Carried Forward\n\n*Generated by \`/pa brief\` — runs.*\n\n---\n> [!tip] Claude's Notes\n> *Generated by x.*\n\n---\n<!-- RAW INPUT BOUNDARY — Everything above -->\n\n## Raw\n`;

describe("journal", () => {
  it("treats the empty template as no content", () => {
    expect(analyzeJournal(TEMPLATE)).toEqual({ hasRaw: false, hasGenerated: false });
  });
  it("detects raw text and generated text", () => {
    expect(analyzeJournal(TEMPLATE + "\nStudied automata\n").hasRaw).toBe(true);
    expect(analyzeJournal(TEMPLATE.replace("*Generated by `/pa brief` — runs.*", "- [ ] do A1")).hasGenerated).toBe(true);
  });
  it("finds the gap from the latest entry with content, not yesterday", () => {
    const s = summarizeJournal(
      [
        { date: "2026-10-02", path: "a", hasRaw: false, hasGenerated: false },
        { date: "2026-09-30", path: "b", hasRaw: true, hasGenerated: false },
        { date: "2026-09-28", path: "c", hasRaw: true, hasGenerated: true },
      ],
      "2026-10-02"
    );
    expect(s).toMatchObject({ todayExists: true, todayHasContent: false, lastContentDate: "2026-09-30", gapDays: 2 });
  });
  it("parses daily note names", () => {
    expect(dailyNameToIso("YYYYMMDD", "20261002")).toBe("2026-10-02");
    expect(dailyNameToIso("YYYY-MM-DD", "2026-10-02")).toBe("2026-10-02");
    expect(dailyNameToIso("YYYYMMDD", "Summary")).toBeUndefined();
  });
});

describe("live radar", () => {
  it("parses loose due text in SAST", () => {
    expect(parseDueText("Mon 5 Oct, 14:00", "2026-10-02")).toBe(Date.parse("2026-10-05T14:00:00+02:00"));
    expect(parseDueText("~16 Oct", "2026-10-02")).toBe(Date.parse("2026-10-16T23:59:00+02:00"));
    expect(parseDueText("TBA", "2026-10-02")).toBeUndefined();
  });
  it("scores weight ÷ fractional days and sorts by score", () => {
    const now = Date.parse("2026-10-02T00:00:00+02:00");
    const rows = scoreRadar(
      [
        { id: "b", name: "B", dueText: "Mon 5 Oct, 14:00", weightText: "40%" },
        { id: "a", name: "A", dueText: "Fri 2 Oct", weightText: "40" },
        { id: "c", name: "C", dueText: "13 Oct", weightText: "$F$" },
        { id: "gone", name: "Old", dueText: "Mon 28 Sep", weightText: "10" },
      ],
      "2026-10-02",
      now
    );
    expect(rows.map((r) => r.id)).toEqual(["a", "b", "c"]);
    expect(rows[0].liveScore).toBeCloseTo(40 / (23.983 / 24), 1);
    expect(rows[2].liveScore).toBeUndefined();
  });
});

describe("engine announcements", () => {
  const task = (over: Record<string, unknown>) =>
    ({ ...parseTasks("n.md", "## Tasks\n- [ ] placeholder task\n")[0], ...over });
  const base = {
    today: "2026-10-02",
    now: Date.parse("2026-10-02T09:00:00+02:00"),
    tasks: [],
    journal: { todayExists: true, todayHasContent: false, lastContentDate: "2026-09-30", gapDays: 2 },
    radar: [],
    duplicates: [],
    mtimeOf: () => undefined,
  };
  it("flags a journal gap and mentions unverified overdue", () => {
    const out = engineAnnouncements({ ...base, tasks: [task({ due: "2026-09-29" })] });
    expect(out).toHaveLength(1);
    expect(out[0].id).toBe("engine:journal-gap:2026-09-30");
    expect(out[0].text).toContain("unverified");
  });
  it("is quiet when the journal is current", () => {
    expect(engineAnnouncements({ ...base, journal: { ...base.journal, gapDays: 0 } })).toEqual([]);
  });
  it("flags 3-week-old overdue and quiet waiting items", () => {
    const out = engineAnnouncements({
      ...base,
      journal: { ...base.journal, gapDays: 0 },
      tasks: [task({ due: "2026-09-01" }), task({ waiting: true, text: "ping Sam" })],
      mtimeOf: () => base.now - 15 * 86_400_000,
    });
    expect(out.map((o) => o.id)).toEqual(["engine:ancient", "engine:waiting-quiet"]);
  });
  it("finds duplicates across files", () => {
    const a = parseTasks("a.md", "## Tasks\n- [ ] Submit the A1 report 📅 2026-10-02\n");
    const b = parseTasks("b.md", "## Tasks\n- [ ] submit the A1 report 📅 2026-10-02\n- [ ] other thing here\n");
    expect(findDuplicates([...a, ...b])).toHaveLength(1);
  });
});
