import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { renderJournal, createJournalText, contextBody, appendToSection, TASKS_BLOCK, BOUNDARY_RE } from "../src/writers/journal";
import { appendRawBlock, applySpellingEdits, isSpellingOnly } from "../src/writers/raw";
import { parseCapture, nextWeekday, weekdayNextWeek } from "../src/writers/capture";
import { replaceRadarTable } from "../src/writers/board";
import { validateOps, locateLine, formatTaskLine, isValidIso, hasDueMarker, TaskOp } from "../src/writers/tasks";
import { parseTasks } from "../src/engine/collectors/tasks";
import { hash } from "../src/writers/hash";
import { coerceState } from "../src/state/schema";

const template = readFileSync(join(__dirname, "fixtures/daily-template.md"), "utf8");
const fmt = (f: string) => ({ "YYYY-MM-DD HH:mm": "2026-10-02 07:00", "YYYY-MM-DD": "2026-10-02", dddd: "Friday", "dddd, MMMM DD, YYYY": "Friday, October 02, 2026" }[f] ?? f);
const fresh = () => createJournalText(template, fmt, { yesterday: "20261001", tomorrow: "20261003" });
const raw = "\n\nstudied automata for 2 hours, did not finish the sheet\nSaw Sam about the project.\n";
const sections = {
  carriedForward: "Two items are **unverified**.",
  priorities: ["Submit A1", "Plan the group project"],
  context: contextBody([{ start: "09:00", end: "10:00", title: "CS343 Lecture", note: "K303" }, { start: "all-day", title: "DS346 A1 due" }], ["weights for CS344"], true),
  notes: "Blunt note.\n\nSecond paragraph.",
};

describe("journal creation from the real template", () => {
  it("resolves placeholders and the nav links", () => {
    const j = fresh();
    expect(j).toContain("date: 2026-10-02");
    expect(j).toContain("# Friday, October 02, 2026");
    expect(j).toContain("*← [[20261001|yesterday]] | [[20261003|tomorrow]] →*");
    expect(j).not.toContain("{{");
  });
});

describe("renderJournal guarantees", () => {
  it("replaces generated sections and leaves the boundary and Raw byte-identical", () => {
    const base = fresh() + raw.trimStart();
    const r = renderJournal(base, sections);
    expect(r.error).toBeUndefined();
    expect(r.changed).toEqual(expect.arrayContaining(["Carried Forward", "Today's Priorities", "Context", "Claude's Notes"]));
    expect(r.text).toContain("1. Submit A1");
    expect(r.text).toContain("- **09:00–10:00** — CS343 Lecture · K303");
    expect(r.text).toContain("> Blunt note.\n>\n> Second paragraph.");
    expect(r.text).toContain(TASKS_BLOCK);
    const tail = (t: string) => t.slice(t.search(BOUNDARY_RE));
    expect(tail(r.text)).toBe(tail(base));
  });
  it("is idempotent", () => {
    const once = renderJournal(fresh(), sections).text;
    expect(renderJournal(once, sections).text).toBe(once);
  });
  it("writes nothing when the boundary marker is missing", () => {
    const noMarker = fresh().replace(/<!-- RAW INPUT BOUNDARY[^>]*-->/, "");
    const r = renderJournal(noMarker, sections);
    expect(r.error).toMatch(/BOUNDARY marker is missing/);
    expect(r.text).toBe(noMarker);
    expect(r.changed).toEqual([]);
  });
  it("never touches a heading-like line inside Raw", () => {
    const base = fresh() + "## Actions\n- [ ] my own task in raw\n## Context\nmine\n";
    const r = renderJournal(base, { context: "new context", actionsAppend: ["- [ ] x 📅 2026-10-03"] });
    expect(r.text.endsWith("## Actions\n- [ ] my own task in raw\n## Context\nmine\n")).toBe(true);
  });
  it("keeps the code-fenced query block from ending a section early", () => {
    const once = renderJournal(fresh(), { carriedForward: "x" }).text;
    const twice = renderJournal(once, { carriedForward: "y", priorities: ["a"] }).text;
    expect(twice.match(/```tasks/g)).toHaveLength(1);
    expect(twice).toContain("1. a");
  });
  it("Actions is append-only: existing prose and user tasks survive, placeholder goes, no duplicates", () => {
    const withUser = fresh().replace(/## Actions\n\n\*Generated by[^\n]*\n/, "## Actions\n\nCarried by reference:\n\n- [ ] user task I typed 📅 2026-10-01\n");
    const line = "- [ ] CS344 hand in A2 📅 2026-10-30";
    const r = renderJournal(withUser, { actionsAppend: [line] });
    expect(r.text).toContain("Carried by reference:");
    expect(r.text).toContain("- [ ] user task I typed 📅 2026-10-01\n" + line);
    expect(renderJournal(r.text, { actionsAppend: [line] }).text).toBe(r.text);
    expect(fresh()).toContain("*Generated by `/pa brief`");
    expect(renderJournal(fresh(), { actionsAppend: [line] }).text).not.toMatch(/## Actions[\s\S]*\*Generated by `\/pa brief`[\s\S]*## Context/);
  });
  it("skips a section the note doesn't have, and says so", () => {
    const old = fresh().replace(/## Context[\s\S]*?---\n\n/, "");
    expect(renderJournal(old, { context: "x" }).skipped).toEqual(["Context"]);
  });
  it("says the calendar wasn't checked rather than 'nothing today'", () => {
    expect(contextBody([], [], false)).toMatch(/not checked/);
    expect(contextBody([], [], true)).toMatch(/Nothing on the calendar/);
  });
});

describe("Raw writes", () => {
  it("appends form answers below the boundary without disturbing existing Raw", () => {
    const base = fresh() + "my earlier words\n";
    const r = appendRawBlock(base, "### Close\n**Done:** a");
    expect(r.error).toBeUndefined();
    expect(r.text.startsWith(base.replace(/\s+$/, ""))).toBe(true);
    expect(r.text.endsWith("### Close\n**Done:** a\n")).toBe(true);
  });
  it("refuses without a boundary", () => {
    expect(appendRawBlock("# no marker", "x").error).toBeTruthy();
  });
  it("accepts typo, case and punctuation fixes only", () => {
    expect(isSpellingOnly("recieve the sheet", "receive the sheet")).toBe(true);
    expect(isSpellingOnly("i did not finish", "I did not finish.")).toBe(true);
    expect(isSpellingOnly("deeplearning defered", "deep learning deferred")).toBe(false); // changes word count
    expect(isSpellingOnly("I did not finish", "I finished everything")).toBe(false);
    expect(isSpellingOnly("failed the test", "passed the test")).toBe(false);
    expect(isSpellingOnly("", "x")).toBe(false);
    expect(isSpellingOnly("did not finish", "did now finish")).toBe(false); // would flip the meaning
    expect(isSpellingOnly("studied for 2 hours", "studied for 3 hours")).toBe(false); // numbers are never spelling
    expect(isSpellingOnly("pass the test", "fail the test")).toBe(false);
  });
  it("applies edits inside Raw only, one match each", () => {
    const base = fresh() + "I recieve the sheet. Studed hard. Studed again.\n";
    const r = applySpellingEdits(base, [
      { find: "recieve", replace: "receive" },
      { find: "Studed", replace: "Studied" }, // appears twice → rejected
      { find: "hard", replace: "easy" }, // not spelling → rejected
      { find: "Carried Forward", replace: "Carried Fwd" }, // above the boundary → not in Raw
    ]);
    expect(r.applied.map((e) => e.find)).toEqual(["recieve"]);
    expect(r.rejected.map((x) => x.reason)).toEqual([
      "text appears more than once in Raw",
      "more than a spelling or punctuation fix",
      "more than a spelling or punctuation fix",
    ]);
    expect(r.text).toContain("I receive the sheet.");
    expect(r.text).toContain("## Carried Forward"); // untouched
  });
});

describe("capture parsing", () => {
  const today = "2026-10-02"; // Friday
  const c = (s: string) => parseCapture(s, today, ["CS343", "CS344", "CS345", "DS346"]);
  it("understands weekdays, relative days and dates", () => {
    expect(c("hand in A2 friday").due).toBe("2026-10-09"); // never today for a bare weekday
    expect(c("email Sam monday").due).toBe("2026-10-05");
    expect(c("send invoice tomorrow").due).toBe("2026-10-03");
    expect(c("review notes today").due).toBe("2026-10-02");
    expect(c("call back in 3 days").due).toBe("2026-10-05");
    expect(c("book flights 14 oct").due).toBe("2026-10-14");
    expect(c("tax return oct 20th").due).toBe("2026-10-20");
    expect(c("renew 5 jan").due).toBe("2027-01-05"); // already past this year
    expect(c("x 2026-11-01").due).toBe("2026-11-01");
    expect(weekdayNextWeek(today, 5)).toBe("2026-10-09");
    expect(c("prep next wednesday").due).toBe("2026-10-07");
    expect(nextWeekday("2026-10-02", 0)).toBe("2026-10-04");
  });
  it("does not mistake ordinary words for dates", () => {
    expect(c("I sat the test and read the sun article").due).toBeUndefined();
    expect(c("Monday.com cleanup").due).toBe("2026-10-05"); // a real weekday word is allowed
    expect(c("wed to the project").due).toBeUndefined(); // short form needs by/on/due
    expect(c("finish it by wed").due).toBe("2026-10-07");
  });
  it("normalises a leading course code so course cards match it", () => {
    const r = c("cs344 hand in A2 friday");
    expect(r.course).toBe("CS344");
    expect(r.text.startsWith("CS344 hand in")).toBe(true);
    expect(c("buy milk").course).toBeUndefined();
  });
});

describe("task op validation", () => {
  const open = parseTasks("Notes/Courses/CS345/CS345 Course Hub.md", "## Tasks\n- [ ] **Group project — BPE DFA tokenization** — repo state at the deadline *is* the submission, 40% 📅 2026-10-05 #task\n- [ ] Send invoice to Sam 📅 2026-10-10\n");
  const ctx = { today: "2026-10-02", openTasks: open };
  const ref = (t: (typeof open)[number]) => ({ path: t.path, line: t.line, expectedText: t.raw });
  const run = (ops: TaskOp[]) => validateOps(ops, ctx);

  it("creates a new dated task", () => {
    const [r] = run([{ op: "create", text: "Book CS344 demo slot", due: "2026-10-12" }]);
    expect(r.verdict).toBe("apply");
  });
  it("rejects invalid or impossible dates", () => {
    expect(run([{ op: "create", text: "x task here", due: "2026-02-30" }])[0].verdict).toBe("reject");
    expect(run([{ op: "create", text: "x task here", due: "friday" }])[0].verdict).toBe("reject");
  });
  it("rejects dates written only in prose", () => {
    const [r] = run([{ op: "create", text: "Hand in the report by Friday" }]);
    expect(r.verdict).toBe("reject");
    expect(r.reason).toMatch(/no 📅/);
  });
  it("drops an exact duplicate", () => {
    const [r] = run([{ op: "create", text: "send invoice to sam", due: "2026-10-10" }]);
    expect(r.verdict).toBe("drop");
    expect(r.reason).toMatch(/duplicate of/);
  });
  it("turns a near-duplicate with a new date into a re-date of the original", () => {
    const [r] = run([{ op: "create", text: "Send the invoice to Sam", due: "2026-10-14" }]);
    expect(r.verdict).toBe("apply");
    expect(r.converted).toMatchObject({ op: "redate", due: "2026-10-14" });
  });
  it("drops a short title that is contained in a longer existing task (real-vault case)", () => {
    const r = run([{ op: "create", text: "Group project — BPE DFA tokenization", due: "2026-10-05" }])[0];
    expect(r.verdict).toBe("drop");
    expect(r.reason).toMatch(/duplicate of/);
    // no date given is fine too
    expect(run([{ op: "create", text: "BPE DFA tokenization group project" }])[0].verdict).toBe("drop");
  });
  it("does not treat contained text as a duplicate when the dates disagree, or the title is tiny", () => {
    expect(run([{ op: "create", text: "Group project BPE DFA tokenization", due: "2026-11-30" }])[0].verdict).toBe("apply");
    expect(run([{ op: "create", text: "Send invoice", due: "2026-10-30" }])[0].verdict).toBe("apply"); // 2 words: too generic
  });
  it("drops the same task proposed twice in one result", () => {
    const rs = run([
      { op: "create", text: "Order the new charger cable", due: "2026-10-09" },
      { op: "create", text: "order new charger cable", due: "2026-10-09" },
    ]);
    expect(rs.map((r) => r.verdict)).toEqual(["apply", "drop"]);
  });
  it("re-dates only existing open tasks, and drops a no-op", () => {
    expect(run([{ op: "redate", ref: ref(open[1]), due: "2026-10-20" }])[0].verdict).toBe("apply");
    expect(run([{ op: "redate", ref: ref(open[1]), due: "2026-10-10" }])[0].verdict).toBe("drop");
    expect(run([{ op: "redate", ref: { path: "x.md", line: 1, expectedText: "- [ ] ghost" }, due: "2026-10-20" }])[0].verdict).toBe("reject");
  });
  it("completion requires the real date and never defaults to today", () => {
    expect(run([{ op: "complete", ref: ref(open[0]) }])[0].verdict).toBe("reject");
    expect(run([{ op: "complete", ref: ref(open[0]), doneDate: "2026-10-09" }])[0].reason).toMatch(/future/);
    expect(run([{ op: "complete", ref: ref(open[0]), doneDate: "2026-09-28" }])[0].verdict).toBe("apply");
  });
  it("locates a drifted line by text and refuses when ambiguous", () => {
    const lines = ["a", "b", "- [ ] t", "c"];
    expect(locateLine(lines, { path: "", line: 0, expectedText: "- [ ] t" })).toEqual({ index: 2 });
    expect(locateLine([...lines, "- [ ] t"], { path: "", line: 0, expectedText: "- [ ] t" })).toEqual({ error: "ambiguous" });
    expect(locateLine(lines, { path: "", line: 0, expectedText: "- [ ] gone" })).toEqual({ error: "not-found" });
  });
  it("formats lines with the due marker, tagging only where the heading wouldn't count it", () => {
    expect(formatTaskLine("CS344 hand in A2", "2026-10-30", false)).toBe("- [ ] CS344 hand in A2 📅 2026-10-30");
    expect(formatTaskLine("- [ ] loose item", undefined, true)).toBe("- [ ] loose item #task");
    expect(hasDueMarker(formatTaskLine("x", "2026-10-30", false))).toBe(true);
    expect(isValidIso("2026-13-01")).toBe(false);
  });
  it("appends under an existing Tasks heading", () => {
    const r = appendToSection("# Hub\n\n## Tasks\n\n- [ ] a\n- [ ] b\n\n## Notes\nx\n", /^##\s+Tasks\b/, ["- [ ] c"]);
    expect(r?.text).toBe("# Hub\n\n## Tasks\n\n- [ ] a\n- [ ] b\n- [ ] c\n\n## Notes\nx\n");
    expect(appendToSection("# Hub\n", /^##\s+Tasks\b/, ["- [ ] c"])).toBeNull();
  });
});

describe("board and state", () => {
  it("swaps only the radar table for the live block", () => {
    const md = "# Board\n\n## 📊 Deadline radar\n\nintro\n\n| Score | A |\n|---|---|\n| 1 | b |\n\n**Read:** x\n\n## Next\n\n| keep | me |\n";
    const out = replaceRadarTable(md)!;
    expect(out).toContain("```pa-radar\n```");
    expect(out).toContain("**Read:** x");
    expect(out).toContain("| keep | me |");
    expect(out).not.toContain("| Score | A |");
    expect(replaceRadarTable(out)).toBeNull();
    expect(replaceRadarTable("# nothing")).toBeNull();
  });
  it("hashes deterministically", () => {
    expect(hash("a")).toBe(hash("a"));
    expect(hash("a")).not.toBe(hash("b"));
  });
  it("migrates the old single pending result to a list", () => {
    const s = coerceState({ schemaVersion: 1, pending: { runId: "r", job: "brief", at: "x", result: {} } });
    expect(s.pending).toHaveLength(1);
    expect(coerceState({ schemaVersion: 1 }).writes).toEqual([]);
  });
});
