import type { TimelineEvent } from "../state/schema";

/**
 * Journal writer. The guarantees live here, not in the prompt:
 *  - nothing at or below the RAW INPUT BOUNDARY marker is ever touched (verified after every render)
 *  - only the named generated sections are replaced; Actions is append-only
 *  - if the marker is missing, nothing is written
 */
export const BOUNDARY_RE = /<!--\s*RAW INPUT BOUNDARY/;
const FENCE = /^\s*(```|~~~)/;
const HEADINGS = {
  carried: /^##\s+Carried Forward\s*$/,
  priorities: /^##\s+Today['’]s Priorities\s*$/,
  actions: /^##\s+Actions\s*$/,
  context: /^##\s+Context\s*$/,
} as const;
const NOTES_CALLOUT = /^>\s*\[![\w-]+\]\s*Claude['’]s Notes/i;

export const TASKS_BLOCK = [
  "```tasks",
  "not done",
  "(heading includes Actions) OR (heading includes Tasks) OR (tag includes #task)",
  "due before today",
  "sort by due",
  "short mode",
  "```",
].join("\n");

export interface JournalSections {
  carriedForward?: string; // commentary; the live query block is appended
  priorities?: string[];
  context?: string; // markdown
  notes?: string; // markdown, becomes the Claude's Notes callout
  actionsAppend?: string[]; // task lines, appended (never replaced)
}

export interface RenderResult {
  text: string;
  changed: string[];
  skipped: string[];
  error?: string;
}

interface Edit {
  start: number; // first line replaced
  end: number; // one past the last line replaced
  lines: string[];
}

/** Index of the first `---` rule or heading after `from`, ignoring anything inside code fences. */
function sectionEnd(lines: string[], from: number): number {
  let fenced = false;
  for (let i = from; i < lines.length; i++) {
    if (FENCE.test(lines[i])) fenced = !fenced;
    if (fenced) continue;
    if (lines[i].trim() === "---" || /^#{1,2}\s/.test(lines[i])) return i;
  }
  return lines.length;
}

export function renderJournal(text: string, s: JournalSections): RenderResult {
  const all = text.split("\n");
  const b = all.findIndex((l) => BOUNDARY_RE.test(l));
  if (b < 0) {
    return { text, changed: [], skipped: [], error: "The RAW INPUT BOUNDARY marker is missing, so nothing was written to this journal." };
  }
  const above = all.slice(0, b);
  const below = all.slice(b);
  const edits: Edit[] = [];
  const changed: string[] = [];
  const skipped: string[] = [];

  const replaceBody = (key: keyof typeof HEADINGS, label: string, body: string) => {
    const h = above.findIndex((l) => HEADINGS[key].test(l));
    if (h < 0) {
      skipped.push(label);
      return;
    }
    edits.push({ start: h + 1, end: sectionEnd(above, h + 1), lines: ["", ...body.trim().split("\n"), ""] });
    changed.push(label);
  };

  if (s.carriedForward !== undefined) {
    const c = s.carriedForward.trim();
    replaceBody("carried", "Carried Forward", `${c ? c + "\n\n" : ""}${TASKS_BLOCK}`);
  }
  if (s.priorities) {
    replaceBody("priorities", "Today's Priorities", s.priorities.length ? s.priorities.map((p, i) => `${i + 1}. ${p}`).join("\n") : "*Nothing prioritised today.*");
  }
  if (s.context !== undefined) replaceBody("context", "Context", s.context);

  if (s.notes !== undefined) {
    const n = above.findIndex((l) => NOTES_CALLOUT.test(l));
    if (n < 0) skipped.push("Claude's Notes");
    else {
      let e = n + 1;
      while (e < above.length && above[e].startsWith(">")) e++;
      const body = s.notes.trim().split("\n").map((l) => (l.trim() ? `> ${l}` : ">"));
      edits.push({ start: n, end: e, lines: ["> [!tip] Claude's Notes", ...body] });
      changed.push("Claude's Notes");
    }
  }

  if (s.actionsAppend?.length) {
    const h = above.findIndex((l) => HEADINGS.actions.test(l));
    if (h < 0) skipped.push("Actions");
    else {
      const end = sectionEnd(above, h + 1);
      const body = above.slice(h + 1, end);
      const fresh = s.actionsAppend.filter((l) => !body.includes(l));
      if (fresh.length) {
        // Drop the template placeholder, keep everything else exactly as it was.
        const kept = body.filter((l) => !/^\*Generated by/.test(l.trim()));
        let last = kept.length - 1;
        while (last >= 0 && kept[last].trim() === "") last--;
        const head = kept.slice(0, last + 1);
        const lines = head.length ? [...head, ...(head[head.length - 1].startsWith("- ") ? [] : [""]), ...fresh, ""] : ["", ...fresh, ""];
        edits.push({ start: h + 1, end, lines });
        changed.push(`Actions (+${fresh.length})`);
      }
    }
  }

  // Apply bottom-up so earlier line numbers stay valid.
  const out = [...above];
  for (const e of edits.sort((a, c) => c.start - a.start)) out.splice(e.start, e.end - e.start, ...e.lines);
  const result = [...out, ...below].join("\n");

  // Invariant: the boundary and everything below it are byte-identical.
  if (result.slice(result.length - below.join("\n").length) !== below.join("\n")) {
    return { text, changed: [], skipped, error: "Refusing to write: the Raw section would have changed." };
  }
  return { text: result, changed, skipped };
}

// ── Section bodies ──────────────────────────────────────────────────────────

export function contextBody(timeline: TimelineEvent[], missing: string[], calendarChecked: boolean): string {
  const lines: string[] = [];
  if (!calendarChecked) {
    lines.push("*The calendar was not checked this run.*");
  } else if (!timeline.length) {
    lines.push("*Nothing on the calendar today.*");
  } else {
    lines.push("**Today's schedule** (calendar, SAST):", "");
    for (const e of timeline) {
      const when = e.start === "all-day" ? "**All day**" : e.end ? `**${e.start}–${e.end}**` : `**${e.start}**`;
      lines.push(`- ${when} — ${e.title}${e.note ? ` · ${e.note}` : ""}`);
    }
  }
  if (missing.length) lines.push("", `**Couldn't check:** ${missing.join("; ")}`);
  return lines.join("\n");
}

/** Replace the {{date:FORMAT}} placeholders and the yesterday/tomorrow nav line of the daily template. */
export function createJournalText(
  template: string,
  fmt: (format: string) => string,
  links: { yesterday: string; tomorrow: string }
): string {
  return template
    .replace(/\{\{date:([^}]+)\}\}/g, (_m, f: string) => fmt(f))
    .replace(/\{\{date\}\}/g, fmt("YYYY-MM-DD"))
    .replace(/\{\{time\}\}/g, fmt("HH:mm"))
    .replace(/^\*←.*→\*$/m, `*← [[${links.yesterday}|yesterday]] | [[${links.tomorrow}|tomorrow]] →*`);
}

export const FALLBACK_TEMPLATE = `---
created: {{date:YYYY-MM-DD HH:mm}}
date: {{date:YYYY-MM-DD}}
day: {{date:dddd}}
tags:
  - daily_notes
---

# {{date:dddd, MMMM DD, YYYY}}

*← yesterday | tomorrow →*

## Carried Forward

---

## Today's Priorities

---

## Actions

---

## Context

---

> [!tip] Claude's Notes
> *Generated by Vault Digest.*

---
<!-- RAW INPUT BOUNDARY — Everything above this line is AI-generated. Write freely below. -->

## Raw
`;

/** Insert task lines at the end of a `## Tasks` / `## Actions` style section of any note. */
export function appendToSection(text: string, heading: RegExp, lines: string[]): { text: string; added: number } | null {
  const all = text.split("\n");
  const h = all.findIndex((l) => heading.test(l));
  if (h < 0) return null;
  let fenced = false;
  let end = all.length;
  for (let i = h + 1; i < all.length; i++) {
    if (FENCE.test(all[i])) fenced = !fenced;
    if (fenced) continue;
    if (/^#{1,6}\s/.test(all[i]) || all[i].trim() === "---" || BOUNDARY_RE.test(all[i])) {
      end = i;
      break;
    }
  }
  const fresh = lines.filter((l) => !all.slice(h + 1, end).includes(l));
  if (!fresh.length) return { text, added: 0 };
  let last = end - 1;
  while (last > h && all[last].trim() === "") last--;
  all.splice(last + 1, 0, ...(last === h ? [""] : []), ...fresh);
  return { text: all.join("\n"), added: fresh.length };
}
