import { daysBetween } from "../../util/dates";

export interface JournalInfo {
  hasRaw: boolean;
  hasGenerated: boolean;
}

export interface JournalEntry extends JournalInfo {
  date: string; // YYYY-MM-DD
  path: string;
}

const BOUNDARY = /<!--\s*RAW INPUT BOUNDARY/;

/** Does this daily note hold anything beyond the empty template? */
export function analyzeJournal(text: string): JournalInfo {
  const b = BOUNDARY.exec(text);
  const above = b ? text.slice(0, b.index) : text;
  const below = b ? text.slice(b.index).split("\n").slice(1).join("\n") : "";

  const hasRaw = below.replace(/^##\s+Raw\s*$/im, "").trim().length > 0;
  const body = above.replace(/^---[\s\S]*?\n---\n/, ""); // frontmatter
  const hasGenerated = body.split("\n").some((l) => {
    const t = l.trim();
    return (
      t !== "" &&
      t !== "---" &&
      !t.startsWith("#") &&
      !t.startsWith("*Generated by") &&
      !t.startsWith("> *Generated by") &&
      !t.startsWith("> [!") &&
      !t.startsWith("*←") &&
      !t.startsWith("<!--")
    );
  });
  return { hasRaw, hasGenerated };
}

export interface JournalSummary {
  todayExists: boolean;
  todayHasContent: boolean;
  /** Date of the latest entry that actually has content. */
  lastContentDate?: string;
  /** Days since that entry (today − last). 0 when today has content. */
  gapDays: number | null;
}

export function summarizeJournal(entries: JournalEntry[], today: string): JournalSummary {
  const sorted = [...entries].filter((e) => e.date <= today).sort((a, b) => b.date.localeCompare(a.date));
  const todayEntry = sorted.find((e) => e.date === today);
  const last = sorted.find((e) => e.hasRaw || e.hasGenerated);
  return {
    todayExists: !!todayEntry,
    todayHasContent: !!todayEntry && (todayEntry.hasRaw || todayEntry.hasGenerated),
    lastContentDate: last?.date,
    gapDays: last ? daysBetween(last.date, today) : null,
  };
}
